<?php

/* custom routes generated by CRUD */
 // Dashboard / Index
 Route::get(
    '/head',
    function () {
        return view('head.index');
    }
)->name('dashboard');

Route::get(
    '/receiver',
    function () {
        return view('receiver.index');
    }
)->name('dashboard');
Route::group(array('prefix' => 'admin/head/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.head.'), function () {

Route::get('heads', ['as'=> 'heads.index', 'uses' => 'Head\HeadController@index']);
Route::post('heads', ['as'=> 'heads.store', 'uses' => 'Head\HeadController@store']);
Route::get('heads/create', ['as'=> 'heads.create', 'uses' => 'Head\HeadController@create']);
Route::put('heads/{heads}', ['as'=> 'heads.update', 'uses' => 'Head\HeadController@update']);
Route::patch('heads/{heads}', ['as'=> 'heads.update', 'uses' => 'Head\HeadController@update']);
Route::get('heads/{id}/delete', ['as' => 'heads.delete', 'uses' => 'Head\HeadController@getDelete']);
Route::get('heads/{id}/confirm-delete', ['as' => 'heads.confirm-delete', 'uses' => 'Head\HeadController@getModalDelete']);
Route::get('heads/{heads}', ['as'=> 'heads.show', 'uses' => 'Head\HeadController@show']);
Route::get('heads/{heads}/edit', ['as'=> 'heads.edit', 'uses' => 'Head\HeadController@edit']);

});

Route::group(array('prefix' => 'head/head/','namespace' => 'Head','middleware' => 'head','as'=>'head.head.'), function () {

    Route::get('heads', ['as'=> 'heads.index', 'uses' => 'Head\HeadController@index']);
    Route::post('heads', ['as'=> 'heads.store', 'uses' => 'Head\HeadController@store']);
    Route::get('heads/create', ['as'=> 'heads.create', 'uses' => 'Head\HeadController@create']);
    Route::put('heads/{heads}', ['as'=> 'heads.update', 'uses' => 'Head\HeadController@update']);
    Route::patch('heads/{heads}', ['as'=> 'heads.update', 'uses' => 'Head\HeadController@update']);
    Route::get('heads/{id}/delete', ['as' => 'heads.delete', 'uses' => 'Head\HeadController@getDelete']);
    Route::get('heads/{id}/confirm-delete', ['as' => 'heads.confirm-delete', 'uses' => 'Head\HeadController@getModalDelete']);
    Route::get('heads/{heads}', ['as'=> 'heads.show', 'uses' => 'Head\HeadController@show']);
    Route::get('heads/{heads}/edit', ['as'=> 'heads.edit', 'uses' => 'Head\HeadController@edit']);
    

    //anticorru

    Route::get('/',['as'=>'index','uses'=>'App\Http\Controllers\Controller@index']);
    Route::get('result',['as'=>'result','uses'=>'App\Http\Controllers\Controller@result']);
    //Route::get('result',['as'=>'result','uses'=>'App\Http\Controllers\Controller@result'])->name('result');
   
    Route::post('create',['as'=>'create','uses'=>'App\Http\Controllers\Controller@created']);
    Route::get('show',['as'=>'show','uses'=>'App\Http\Controllers\Controller@show']);
    Route::get('update',['as'=>'update','uses'=>'App\Http\Controllers\Controller@update']);
    Route::get('delete',['as'=>'delete','uses'=>'App\Http\Controllers\Controller@delete']);

    //Complient Reciver route
    
    // //Complient Reciver route
    // Route::get('reciver',['as'=>'reciver','uses'=>'App\Http\Controllers\ReciverController@recive']);
    // Route::get('details_r/{details_r}',['as'=>'details_r','uses'=>'App\Http\Controllers\ReciverController@details_r']);
    // Route::post('commentrec/',['as'=>'commentrec','uses'=>'App\Http\Controllers\ReciverController@commentrec']);

    //complient  head route
    Route::get('head',['as'=>'head','uses'=>'App\Http\Controllers\HeadController@head']);
    Route::get('details/{details}',['as'=>'details','uses'=>'App\Http\Controllers\HeadController@details']);
    Route::post('comment/',['as'=>'comment','uses'=>'Head\HeadController@comment']);



    


    });
Route::group(array('prefix' => 'receiver/receiver/','namespace' => 'Receiver','middleware' => 'receiver','as'=>'receiver.receiver.'), function () {

Route::get('receivers', ['as'=> 'receivers.index', 'uses' => 'Receiver\ReceiverController@index']);
Route::post('receivers', ['as'=> 'receivers.store', 'uses' => 'Receiver\ReceiverController@store']);
Route::get('receivers/create', ['as'=> 'receivers.create', 'uses' => 'Receiver\ReceiverController@create']);
Route::put('receivers/{receivers}', ['as'=> 'receivers.update', 'uses' => 'Receiver\ReceiverController@update']);
Route::patch('receivers/{receivers}', ['as'=> 'receivers.update', 'uses' => 'Receiver\ReceiverController@update']);
Route::get('receivers/{id}/delete', ['as' => 'receivers.delete', 'uses' => 'Receiver\ReceiverController@getDelete']);
Route::get('receivers/{id}/confirm-delete', ['as' => 'receivers.confirm-delete', 'uses' => 'Receiver\ReceiverController@getModalDelete']);
Route::get('receivers/{receivers}', ['as'=> 'receivers.show', 'uses' => 'Receiver\ReceiverController@show']);
Route::get('receivers/{receivers}/edit', ['as'=> 'receivers.edit', 'uses' => 'Receiver\ReceiverController@edit']);



//receiver

    //anticorru

    Route::get('/',['as'=>'index','uses'=>'App\Http\Controllers\Controller@index']);
    Route::get('result',['as'=>'result','uses'=>'App\Http\Controllers\Controller@result']);
    //Route::get('result',['as'=>'result','uses'=>'App\Http\Controllers\Controller@result'])->name('result');
   
    Route::post('create',['as'=>'create','uses'=>'App\Http\Controllers\Controller@created']);
    Route::get('show',['as'=>'show','uses'=>'App\Http\Controllers\Controller@show']);
    Route::get('update',['as'=>'update','uses'=>'App\Http\Controllers\Controller@update']);
    Route::get('delete',['as'=>'delete','uses'=>'App\Http\Controllers\Controller@delete']);

    //Complient Reciver route
    
    //Complient Reciver route
    Route::get('receiver',['as'=>'receiver','uses'=>'Receiver\ReceiverController@receive']);
    Route::get('details_r/{details_r}',['as'=>'details_r','uses'=>'Receiver\ReceiverController@details_r']);
    Route::post('commentrec/',['as'=>'commentrec','uses'=>'Receiver\ReceiverController@commentrec']);






    //complient  head route
    // Route::get('head',['as'=>'head','uses'=>'App\Http\Controllers\HeadController@head']);
    // Route::get('details/{details}',['as'=>'details','uses'=>'App\Http\Controllers\HeadController@details']);
    // Route::post('comment/',['as'=>'comment','uses'=>'Head\HeadController@comment']);


});
Route::group(array('prefix' => 'admin/receiver/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.receiver.'), function () {

    Route::get('receivers', ['as'=> 'receivers.index', 'uses' => 'Receiver\ReceiverController@index']);
    Route::post('receivers', ['as'=> 'receivers.store', 'uses' => 'Receiver\ReceiverController@store']);
    Route::get('receivers/create', ['as'=> 'receivers.create', 'uses' => 'Receiver\ReceiverController@create']);
    Route::put('receivers/{receivers}', ['as'=> 'receivers.update', 'uses' => 'Receiver\ReceiverController@update']);
    Route::patch('receivers/{receivers}', ['as'=> 'receivers.update', 'uses' => 'Receiver\ReceiverController@update']);
    Route::get('receivers/{id}/delete', ['as' => 'receivers.delete', 'uses' => 'Receiver\ReceiverController@getDelete']);
    Route::get('receivers/{id}/confirm-delete', ['as' => 'receivers.confirm-delete', 'uses' => 'Receiver\ReceiverController@getModalDelete']);
    Route::get('receivers/{receivers}', ['as'=> 'receivers.show', 'uses' => 'Receiver\ReceiverController@show']);
    Route::get('receivers/{receivers}/edit', ['as'=> 'receivers.edit', 'uses' => 'Receiver\ReceiverController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('complaints', ['as'=> 'complaints.index', 'uses' => 'ComplaintsController@index']);
Route::post('complaints', ['as'=> 'complaints.store', 'uses' => 'ComplaintsController@store']);
Route::get('complaints/create', ['as'=> 'complaints.create', 'uses' => 'ComplaintsController@create']);
Route::put('complaints/{complaints}', ['as'=> 'complaints.update', 'uses' => 'ComplaintsController@update']);
Route::patch('complaints/{complaints}', ['as'=> 'complaints.update', 'uses' => 'ComplaintsController@update']);
Route::get('complaints/{id}/delete', ['as' => 'complaints.delete', 'uses' => 'ComplaintsController@getDelete']);
Route::get('complaints/{id}/confirm-delete', ['as' => 'complaints.confirm-delete', 'uses' => 'ComplaintsController@getModalDelete']);
Route::get('complaints/{complaints}', ['as'=> 'complaints.show', 'uses' => 'ComplaintsController@show']);
Route::get('complaints/{complaints}/edit', ['as'=> 'complaints.edit', 'uses' => 'ComplaintsController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('messages', ['as'=> 'messages.index', 'uses' => 'MessageController@index']);
Route::post('messages', ['as'=> 'messages.store', 'uses' => 'MessageController@store']);
Route::get('messages/create', ['as'=> 'messages.create', 'uses' => 'MessageController@create']);
Route::put('messages/{messages}', ['as'=> 'messages.update', 'uses' => 'MessageController@update']);
Route::patch('messages/{messages}', ['as'=> 'messages.update', 'uses' => 'MessageController@update']);
Route::get('messages/{id}/delete', ['as' => 'messages.delete', 'uses' => 'MessageController@getDelete']);
Route::get('messages/{id}/confirm-delete', ['as' => 'messages.confirm-delete', 'uses' => 'MessageController@getModalDelete']);
Route::get('messages/{messages}', ['as'=> 'messages.show', 'uses' => 'MessageController@show']);
Route::get('messages/{messages}/edit', ['as'=> 'messages.edit', 'uses' => 'MessageController@edit']);

});
